-- AlterTable
ALTER TABLE "Shift" ALTER COLUMN "monday" SET DEFAULT ARRAY[]::INTEGER[],
ALTER COLUMN "tuesday" SET DEFAULT ARRAY[]::INTEGER[],
ALTER COLUMN "wednesday" SET DEFAULT ARRAY[]::INTEGER[],
ALTER COLUMN "thursday" SET DEFAULT ARRAY[]::INTEGER[],
ALTER COLUMN "friday" SET DEFAULT ARRAY[]::INTEGER[],
ALTER COLUMN "saturday" SET DEFAULT ARRAY[]::INTEGER[],
ALTER COLUMN "sunday" SET DEFAULT ARRAY[]::INTEGER[];
