-- AlterTable
ALTER TABLE "HistoryShift" ALTER COLUMN "startDate" DROP DEFAULT,
ALTER COLUMN "startDate" SET DATA TYPE TEXT,
ALTER COLUMN "endDate" DROP DEFAULT,
ALTER COLUMN "endDate" SET DATA TYPE TEXT;
